version: 2.1
jobs:
  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6
    steps:
      - checkout
      - run:
          name: Pack
          command:
            SANITIZED_VERSION=`echo $CIRCLE_TAG | sed "s/-alpha//"`
            dotnet pack Ponder -p:PackageVersion=$CIRCLE_TAG -p:Version=$CIRCLE_TAG -p:AssemblyVersion=$SANITIZED_VERSION -o .
      - run:
          name: Publish
          command:
            dotnet nuget push dotnet-ponder.${CIRCLE_TAG}.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+.[0-9]+.[0-9]+(-alpha)?/
